<script type="text/javascript">
    
    ;(function($) {

        $(document).ready(function(){
            
            $("#test-rides").rideManagement({});
            $("#alley-left").adManagement({priority: 0});
            $("#alley-right").adManagement({priority: 1});
            
        });                

    }(jQuery));
    
</script>

<section style="border: 0px solid orange;margin:0 1% 0 1%;">
    <div id="alley-left" class="col span_side"></div>
    <div id="test-rides" class="col span_center"></div>
    <div id="alley-right" class="col span_side"></div>
</section>

