<script type="text/javascript">
    
    ;(function($) {
        
        $(document).ready(function(){
        
            $('#site-sign-in').button().click(function(){
                
            });
            
            $('#site-sign-up').button().click(function(){
                
            });                        
        
        });
        
    }(jQuery));
    
</script>

<section>
    <div style="font-size: 12px; margin: 0 auto; margin-top: 100px; width: 50%;">

        <div style="float: left;">
            <form>
                <div>Sign In</div>
                <div style="margin-top:3px;">
                    <label for="" style="display: inline-block; width:75px;">User Name:</label><input type="text" id="" name="" />
                </div>
                <div style="margin-top:3px;">
                    <label for="" style="display: inline-block; width:75px;">Password:</label><input type="password" id="" name="" />
                </div>
                <div style="margin-top: 10px; text-align: center;">
                    <button id="site-sign-in" name="" style="width: 125px;">Submit</button>
                </div>                
            </form>
        </div>
        <div style="float: left; border-left: 3px solid #465a9b; margin-left: 15px; padding-left: 15px;">
            <form>
                <div>Sign Up</div>
                <div style="margin-top:3px;">
                    <label for="" style="display: inline-block; width:75px;">User Name:</label><input type="text" id="" name="" />
                </div>
                <div style="margin-top:3px;">
                    <label for="" style="display: inline-block; width:75px;">Password:</label><input type="password" id="" name="" />
                </div>
                <div style="margin-top: 10px; text-align: center;">
                    <button id="site-sign-up" name="" style="width: 125px;">Submit</button>
                </div>                
            </form>
        </div>            
        
    </div>
    <div style="clear: both;margin-bottom: 100px;"></div>
</section>