<style type="text/css">
    
    #bottom-menu {
        width: 100%;
        z-index: 9999;
        padding-bottom: 10px;
        font-size: 11px;
        color: #999;
        /*
        position: fixed;
        bottom: 0px;
        */
        background-color: #fff;
        border: 0px solid #333;
        margin-top: 10px;
    }
    
    #bottom-menu-left {
        float:left;
        margin-left: 15px;
    }
    
    #bottom-menu-right {
        float:right;
        margin-bottom: 30px;
        margin-right: 15px;
    }
    
    #bottom-menu-right ul {
        list-style-type: none;
        padding: 0; 
        margin: 0;         
    }
    
    #bottom-menu-right ul li {
        display: inline;
        padding: 0 10px;
    }    
    
    #bottom-menu-right a {
        color: #999;
        text-decoration: none;
    }
    
    #bottom-menu-right a:hover {
        color: #666;
    }
    
    #bottom-menu-top {
        border-bottom: 1px solid #666;
        clear: both;
        width: 98%;
        margin-left: auto;
        margin-right: auto;
    }        
    
</style>

<div id="bottom-menu">
    <footer>
        <div id="bottom-menu-top"></div>
        <div id="bottom-menu-left">
            3 Wilton Drive, Allendale, NJ 07401 | Phone: 201.344.3456 | <a href="mailto:jon@redbonesolutions.com" class="bottom">jon@redbonesolutions.com</a>
        </div>
        <div id="bottom-menu-right">
            <a href="/">Redbone Solutions, LLC</a>
        </div>        
    </footer>
</div>