<style type="text/css">
    
    #top-menu {
        border: 0px solid green;
        width: 100%;
        position: fixed;
        top: 0px;
        z-index: 9999;
        padding-top: 10px;
        background-color: #fff;        
    }
    
    #top-menu-left {
        float:left;
        margin-left: 10px;
    }
    
    #top-menu-right {
        float:right;
        margin-top: 30px;
        margin-right: 10px;
    }
    
    #top-menu-right ul {
        list-style-type: none;
        padding: 0; 
        margin: 0;         
    }
    
    #top-menu-right ul li {
        display: inline;
        padding: 0 10px;
    }    
    
    #top-menu-right ul li a {
        color: #666;
        font-size: 13px;
        text-decoration: none;
    }
    
    #top-menu-right ul li a:hover {
        color: #333;
    }
    
    #top-menu-bottom {
        border-bottom: 1px solid #666;
        clear: both;
        width: 98%;
        margin-left: auto;
        margin-right: auto;
    }
    
    
    
</style>

<div id="top-menu">
    <header>
        <div id="top-menu-left">
            <a href="/"><img src="/images/logo/rs-logo.jpg" alt="Web Development New Jersey Redbone Solutions"></a>
        </div>
        <div id="top-menu-right">
            <nav>
                <ul>
                    <?php echo Application_Plugin_Lib::loggedInAs();?>
                </ul>                        
            </nav>
        </div>
        <div id="top-menu-bottom"></div>        
    </header>
</div>